# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82126bf5f70024c96eee05bf3a34dd416bc8c4875ecbd0e7de0099ef05ce850e016267eff77362f3ee0e76c8bd3b3a17fbb9bec19804a50e1824fb77ba918f40

test:
  secret_key_base: 9549ae591fea2b5e04050d6d4b1cb1ed4d28d032dcb95de3a11dd4a927846a78ae46b29bde5eddf24cf7c41b282b26ce5c00c3ae43d90330c184c7a44c85bdb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
